export const icons = {
  arrow: {
    left: "/assets/icons/arrow/left.svg",
    right: "/assets/icons/arrow/right.svg",
  },
  checkbox: {
    active: "/assets/icons/checkbox/active.svg",
    inactive: "/assets/icons/checkbox/inactive.svg",
  },
  chevron: {
    down: "/assets/icons/chevron/down.svg",
    left: "/assets/icons/chevron/left.svg",
    right: "/assets/icons/chevron/right.svg",
    up: "/assets/icons/chevron/up.svg",
  },
  radio: {
    active: "/assets/icons/active.svg",
    inactive: "/assets/icons/inactive.svg",
  },
  alertCircle: "/assets/icons/alertCircle.svg",
  bell: "/assets/icons/bell.svg",
  check: "/assets/icons/check.svg",
  checkCircle: "/assets/icons/checkCircle.svg",
  edit: "/assets/icons/edit.svg",
  fileText: "/assets/icons/fileText.svg",
  helpCircle: "/assets/icons/helpCircle.svg",
  login: "l/assets/icons/ogin.svg",
  logout: "/assets/icons/logout.svg",
  megaphoneL: "m/assets/icons/egaphoneL.svg",
  megaphoneR: "/assets/icons/megaphoneR.svg",
  plus: "/assets/icons/plus.svg",
  plusCircle: "/assets/icons/plusCircle.svg",
  scale: "/assets/icons/scale.svg",
  send: "/assets/icons/send.svg",
  setting: "/assets/icons/setting.svg",
  trash: "/assets/icons/trash.svg",
  userMinus: "/assets/icons/userMinus.svg",
  userPlus: "/assets/icons/userPlus.svg",
  userCancel: "/assets/icons/userCancel.svg",
  cancel: "/assets/icons/cancel.svg",
  cancelCircle: "/assets/icons/cancelCircl.svge",
};
